name: Jest + SonarCloud - NodeJS CI

on:
  push:
    branches: 
      - '**'        # todas as branches
      - '!documentacao'   # exceto documentacao
  pull_request:
    branches: 
      - '**'        # todas as branches
      - '!documentacao'   # exceto documentacao
defaults:
  run:
    working-directory: api
jobs:

  db:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - name: Create DB
      run: npx sequelize db:create
      
    - name: Migrate Database
      run: npx sequelize db:migrate
      
    - name: Connect to PostgreSQL
      run: node client.js
      env:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }} 
        
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
      
    - name: Run Tests
      run: npm test
